apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-juicefs-prd
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-prd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  csi.storage.k8s.io/node-publish-secret-name: juicefs-prd-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
  csi.storage.k8s.io/controller-expand-secret-name: juicefs-prd-secret   
  csi.storage.k8s.io/controller-expand-secret-namespace: juicefs
  pathPattern: "${.pvc.namespace}-${.pvc.name}"
mountOptions:
  - cache-size=0
reclaimPolicy: Delete
allowVolumeExpansion: true     