apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  network:
    provider: host
    addressRanges:
      # 如果只有 1 条网络，则移除 cluster 配置
      # 如果有 2 条网络，根据实际的宿主机网络设置 public 和 cluster 网段
      public:
        # 用于提供给存储集群外部访问的网段
        - 10.0.0.0/22
      cluster:
        # 用于提供给存储集群内数据复制的网段
        - 192.168.100.0/24
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/storage
                  operator: Exists
