apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: conda
patches:
- path: ingress.yaml
- path: pvc.yaml
secretGenerator:
- files:
  - config.toml
  name: conda-config
  type: Opaque
  behavior: replace
