apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- namespace.yaml
- ingress.yaml
secretGenerator:
- files:
  - config.toml
  name: conda-config
  type: Opaque
