apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-developer
rules:
- apiGroups:
    - ""
  resources:
    - "namespaces"
  verbs:
    - get
    - list
    - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-developer
subjects:
  - kind: ServiceAccount
    name: harbor-developer
    namespace: sa-management
