apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harbor-developer
  namespace: harbor
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harbor-developer
  namespace: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harbor-developer
subjects:
  - kind: ServiceAccount
    name: harbor-developer
    namespace: sa-management