apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: harbor-developer
  namespace: sa-management
  annotations:
    kubernetes.io/service-account.name: harbor-developer
