apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb
spec:
  addresses:
    - 10.128.0.100-10.128.0.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb
spec:
  ipAddressPools:
    - default
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/control-plane: "true"
  interfaces:
    - eth0
